tap "adoptopenjdk/openjdk"
tap "azure/kubelogin"
tap "derailed/k9s"
tap "drone/drone"
tap "hashicorp/tap"
tap "hidetatz/tap"
tap "homebrew/bundle"
tap "jjuarez/tap-1"
tap "robscott/tap"
tap "syncdk/yawsso"
tap "tilt-dev/tap"
brew "python@3.11"
brew "ansible"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "awscli"
brew "python@3.10"
brew "azure-cli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "brew-gem"
brew "caddy"
brew "cfn-lint"
brew "cilium-cli"
brew "glib"
brew "libidn2"
brew "unbound"
brew "gnutls"
brew "qemu"
brew "colima"
brew "coreutils"
brew "cowsay"
brew "csvkit"
brew "ctags"
brew "curl"
brew "diff-so-fancy"
brew "dive"
brew "docker"
brew "docker-credential-helper-ecr", link: false
brew "docutils"
brew "duff"
brew "exa"
brew "findutils"
brew "flake8"
brew "fontconfig"
brew "unixodbc"
brew "freetds"
brew "fx"
brew "fzf"
brew "libavif"
brew "gd"
brew "git"
brew "git-delta"
brew "gitlab-runner"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "gomplate"
brew "grep"
brew "hadolint"
brew "helm"
brew "helmfile"
brew "hexyl"
brew "htop"
brew "infracost"
brew "jenv"
brew "oniguruma"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "kops"
brew "krb5"
brew "krew"
brew "kube-linter"
brew "kube-ps1"
brew "kubectx"
brew "kubespy"
brew "libfido2"
brew "logcli"
brew "mas"
brew "openjdk"
brew "maven"
brew "minikube"
brew "most"
brew "mysql"
brew "newrelic-cli"
brew "nghttp2"
brew "node"
brew "nvm"
brew "openconnect"
brew "packer"
brew "pandoc"
brew "php"
brew "pipenv"
brew "podman"
brew "postgresql@14"
brew "virtualenv"
brew "pre-commit"
brew "pyenv"
brew "pyenv-virtualenv"
brew "tcl-tk", link: false
brew "python@3.8"
brew "python@3.9"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "serverless"
brew "shellcheck"
brew "sops"
brew "ssh-copy-id"
brew "stern"
brew "telnet"
brew "terraform"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "tfsec"
brew "tig"
brew "tree"
brew "vifm"
brew "wget"
brew "wimlib"
brew "yq"
brew "azure/kubelogin/kubelogin"
brew "derailed/k9s/k9s"
brew "hashicorp/tap/terraform-ls"
brew "jjuarez/tap-1/kubecolor"
brew "robscott/tap/kube-capacity"
brew "syncdk/yawsso/yawsso"
brew "tilt-dev/tap/tilt"
cask "alfred", args: { appdir: "/Applications" }
cask "atom", args: { appdir: "/Applications" }
cask "chromium"
cask "finch"
cask "maccy"
cask "ngrok", args: { appdir: "/Applications" }
cask "pgadmin4", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "powershell", args: { appdir: "/Applications" }
cask "redisinsight"
cask "session-manager-plugin"
cask "tunnelblick", args: { appdir: "/Applications" }
cask "utm"
cask "vagrant", args: { appdir: "/Applications" }
mas "Calendars", id: 415181149
mas "Craft", id: 1487937127
mas "DaisyDisk", id: 411643860
mas "Focus To-Do", id: 1258530160
mas "GarageBand", id: 682658836
mas "Gifox", id: 1461845568
mas "iMovie", id: 408981434
mas "Keeper Password Manager", id: 414781829
mas "Keynote", id: 409183694
mas "Kindle Classic", id: 405399194
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WhatsApp", id: 1147396723
vscode "1000ch.svgo"
vscode "4ops.packer"
vscode "4ops.terraform"
vscode "alefragnani.bookmarks"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "antonkovalyov.soy"
vscode "codeium.codeium"
vscode "danielthielking.aws-cloudformation-yaml"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "eamodio.gitlens"
vscode "eastman.vscode-cfn-nag"
vscode "erd0s.terraform-autocomplete"
vscode "esbenp.prettier-vscode"
vscode "exiasr.hadolint"
vscode "genuitecllc.codetogether-onpremises"
vscode "github.vscode-github-actions"
vscode "gitlab.gitlab-workflow"
vscode "golang.go"
vscode "hashicorp.hcl"
vscode "hashicorp.terraform"
vscode "hookyqr.beautify"
vscode "huntertran.auto-markdown-toc"
vscode "infracost.infracost"
vscode "jetmartin.bats"
vscode "johnpapa.vscode-peacock"
vscode "kddejong.vscode-cfn-lint"
vscode "kevinglasson.cornflakes-linter"
vscode "l13rary.l13-diff"
vscode "marcostazi.vs-code-vagrantfile"
vscode "maxird.jinja-fold"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "mrmlnc.vscode-duplicate"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "ms-vsliveshare.vsliveshare"
vscode "oderwat.indent-rainbow"
vscode "pnp.polacode"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "run-at-scale.terraform-doc-snippets"
vscode "ryu1kn.partial-diff"
vscode "samuelcolvin.jinjahtml"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "simonsiefke.svg-preview"
vscode "sirtori.indenticator"
vscode "tbutterwith.bosun"
vscode "timonwong.shellcheck"
vscode "timvaneker.serverless-snippets"
vscode "tuxtina.json2yaml"
vscode "tyriar.sort-lines"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vue.volar"
vscode "wholroyd.jinja"
vscode "withfig.fig"
